### ISSUE TITLE
TDK Switching Regulator Upload

### ISSUE THREAD

**Issue by sabinoj** [chicagoedt/gEDA_Symbols#2]
@andrewpable Can you merge and upload the TDK switching regulator schematic to the repository, please.

**Comment by andrewpable** [comment]
I just commited both my updated gEDA_symbols and gEDA footprints, I hope this is good for you john.

**Comment by andrewpable** [comment]
I just closed the issue, hopefully that is good enough.

**Comment by l0g1x** [comment]
@andrewpable you need to submit a pull request for it to be in the 'upstream' (global) repository. Go to your fork, and click the square green button in upper-ish left corner
